name: Build and Deploy to Cloud Run

# This workflow runs on pushes to the 'main' branch
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  # Example: us-central1
  REGION: 'asia-south1'
  # The name of your Artifact Registry repository
  REPO_NAME: 'icure-frontend'
  # The name you want for your Cloud Run service
  SERVICE_NAME: 'icure-frontend'

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: DEBUG - Check if secret is present
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "Error: The GCP_SA_KEY secret is not available or is empty."
            exit 1
          else
            echo "Success: The GCP_SA_KEY secret was found."
          fi
          
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build the Docker image and push it to Artifact Registry
      # The image is tagged with the GitHub commit SHA for versioning
      - name: Build and Push Docker Image
        run: |-
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --project=${{ env.PROJECT_ID }}
