import * as yup from "yup";

export const assessmentSchema = yup.object().shape({
    patientId: yup.string().required('Patient ID is required'),

    // Chief Complaint Section
    chiefComplaintDescription: yup.string().required('Chief Complaint description is required').max(500, 'Max 500 characters'),

    // Pain Evaluation Section
    painOnset: yup.string().optional().max(100, 'Max 100 characters'),
    painDuration: yup.string().optional().max(100, 'Max 100 characters'),
    painLocation: yup.string().optional().max(200, 'Max 200 characters'),
    painType: yup.string().optional().max(100, 'Max 100 characters'),
    aggravatingFactors: yup.string().optional().max(200, 'Max 200 characters'),
    relievingFactors: yup.string().optional().max(200, 'Max 200 characters'),
    painScale: yup.number().min(0).max(10).required('Pain scale is required').typeError('Pain scale must be a number'),
    painFrequency: yup.string().optional().max(100, 'Max 100 characters'),
    painRadiation: yup.string().optional().max(200, 'Max 200 characters'),
    painTiming: yup.string().optional().max(100, 'Max 100 characters'),
    functionalLimitation: yup.string().optional().max(300, 'Max 300 characters'),

    // Palpation
    palpationFindings: yup.string().optional().max(500, 'Max 500 characters'),

    // Associated Problems
    associatedProblems: yup.string().optional().max(500, 'Max 500 characters'),

    muscularEvaluation: yup.object().shape({
      spine_cervical_flexion: yup.string().optional(),
      spine_cervical_extension: yup.string().optional(),
      spine_cervical_lateral_flexion_left: yup.string().optional(),
      spine_cervical_lateral_flexion_right: yup.string().optional(),
      spine_cervical_rotation_left: yup.string().optional(),
      spine_cervical_rotation_right: yup.string().optional(),
      spine_thoracic_extension: yup.string().optional(),
      spine_thoracic_rotation_left: yup.string().optional(),
      spine_thoracic_rotation_right: yup.string().optional(),
      spine_lumbar_flexion: yup.string().optional(),
      spine_lumbar_extension: yup.string().optional(),
      spine_lumbar_lateral_flexion_left: yup.string().optional(),
      spine_lumbar_lateral_flexion_right: yup.string().optional(),
      spine_lumbar_rotation_left: yup.string().optional(),
      spine_lumbar_rotation_right: yup.string().optional(),
      upper_limb_shoulder_flexion_left: yup.string().optional(),
      upper_limb_shoulder_flexion_right: yup.string().optional(),
      upper_limb_shoulder_extension_left: yup.string().optional(),
      upper_limb_shoulder_extension_right: yup.string().optional(),
      upper_limb_shoulder_abduction_left: yup.string().optional(),
      upper_limb_shoulder_abduction_right: yup.string().optional(),
      upper_limb_shoulder_adduction_left: yup.string().optional(),
      upper_limb_shoulder_adduction_right: yup.string().optional(),
      upper_limb_shoulder_internal_rotation_left: yup.string().optional(),
      upper_limb_shoulder_internal_rotation_right: yup.string().optional(),
      upper_limb_shoulder_external_rotation_left: yup.string().optional(),
      upper_limb_shoulder_external_rotation_right: yup.string().optional(),
      upper_limb_elbow_flexion_left: yup.string().optional(),
      upper_limb_elbow_flexion_right: yup.string().optional(),
      upper_limb_elbow_extension_left: yup.string().optional(),
      upper_limb_elbow_extension_right: yup.string().optional(),
      upper_limb_forearm_supination_left: yup.string().optional(),
      upper_limb_forearm_supination_right: yup.string().optional(),
      upper_limb_forearm_pronation_left: yup.string().optional(),
      upper_limb_forearm_pronation_right: yup.string().optional(),
      upper_limb_wrist_flexion_left: yup.string().optional(),
      upper_limb_wrist_flexion_right: yup.string().optional(),
      upper_limb_wrist_extension_left: yup.string().optional(),
      upper_limb_wrist_extension_right: yup.string().optional(),
      upper_limb_wrist_radial_deviation_left: yup.string().optional(),
      upper_limb_wrist_radial_deviation_right: yup.string().optional(),
      upper_limb_wrist_ulnar_deviation_left: yup.string().optional(),
      upper_limb_wrist_ulnar_deviation_right: yup.string().optional(),
      upper_limb_hand_finger_flexion_left: yup.string().optional(),
      upper_limb_hand_finger_flexion_right: yup.string().optional(),
      upper_limb_hand_finger_extension_left: yup.string().optional(),
      upper_limb_hand_finger_extension_right: yup.string().optional(),
      upper_limb_hand_finger_abduction_left: yup.string().optional(),
      upper_limb_hand_finger_abduction_right: yup.string().optional(),
      upper_limb_hand_finger_adduction_left: yup.string().optional(),
      upper_limb_hand_finger_adduction_right: yup.string().optional(),
      upper_limb_hand_thumb_opposition_left: yup.string().optional(),
      upper_limb_hand_thumb_opposition_right: yup.string().optional(),
      upper_limb_hand_grip_strength_left: yup.string().optional(),
      upper_limb_hand_grip_strength_right: yup.string().optional(),
      lower_limb_hip_flexion_left: yup.string().optional(),
      lower_limb_hip_flexion_right: yup.string().optional(),
      lower_limb_hip_extension_left: yup.string().optional(),
      lower_limb_hip_extension_right: yup.string().optional(),
      lower_limb_hip_abduction_left: yup.string().optional(),
      lower_limb_hip_abduction_right: yup.string().optional(),
      lower_limb_hip_adduction_left: yup.string().optional(),
      lower_limb_hip_adduction_right: yup.string().optional(),
      lower_limb_hip_internal_rotation_left: yup.string().optional(),
      lower_limb_hip_internal_rotation_right: yup.string().optional(),
      lower_limb_hip_external_rotation_left: yup.string().optional(),
      lower_limb_hip_external_rotation_right: yup.string().optional(),
      lower_limb_knee_flexion_left: yup.string().optional(),
      lower_limb_knee_flexion_right: yup.string().optional(),
      lower_limb_knee_extension_left: yup.string().optional(),
      lower_limb_knee_extension_right: yup.string().optional(),
      lower_limb_ankle_dorsiflexion_left: yup.string().optional(),
      lower_limb_ankle_dorsiflexion_right: yup.string().optional(),
      lower_limb_ankle_plantarflexion_left: yup.string().optional(),
      lower_limb_ankle_plantarflexion_right: yup.string().optional(),
      lower_limb_ankle_inversion_left: yup.string().optional(),
      lower_limb_ankle_inversion_right: yup.string().optional(),
      lower_limb_ankle_eversion_left: yup.string().optional(),
      lower_limb_ankle_eversion_right: yup.string().optional(),
      lower_limb_ankle_toe_flexion_left: yup.string().optional(),
      lower_limb_ankle_toe_flexion_right: yup.string().optional(),
      lower_limb_ankle_toe_extension_left: yup.string().optional(),
      lower_limb_ankle_toe_extension_right: yup.string().optional(),
      muscularEvaluation_notes: yup.string().optional(),
    }).optional(),

    jointEvaluation: yup.object().shape({
      joint_spine_cervical_flexion_rom: yup.string().optional(),
      joint_spine_cervical_flexion_notes: yup.string().optional(),
      joint_spine_cervical_extension_rom: yup.string().optional(),
      joint_spine_cervical_extension_notes: yup.string().optional(),
      joint_spine_cervical_lateral_flexion_left_rom: yup.string().optional(),
      joint_spine_cervical_lateral_flexion_left_notes: yup.string().optional(),
      joint_spine_cervical_lateral_flexion_right_rom: yup.string().optional(),
      joint_spine_cervical_lateral_flexion_right_notes: yup.string().optional(),
      joint_spine_cervical_rotation_left_rom: yup.string().optional(),
      joint_spine_cervical_rotation_left_notes: yup.string().optional(),
      joint_spine_cervical_rotation_right_rom: yup.string().optional(),
      joint_spine_cervical_rotation_right_notes: yup.string().optional(),
      joint_spine_cervical_special_tests: yup.string().optional(),
      joint_spine_thoracic_extension_rom: yup.string().optional(),
      joint_spine_thoracic_extension_notes: yup.string().optional(),
      joint_spine_thoracic_rotation_left_rom: yup.string().optional(),
      joint_spine_thoracic_rotation_left_notes: yup.string().optional(),
      joint_spine_thoracic_rotation_right_rom: yup.string().optional(),
      joint_spine_thoracic_rotation_right_notes: yup.string().optional(),
      joint_spine_thoracic_special_tests: yup.string().optional(),
      joint_spine_lumbar_flexion_rom: yup.string().optional(),
      joint_spine_lumbar_flexion_notes: yup.string().optional(),
      joint_spine_lumbar_extension_rom: yup.string().optional(),
      joint_spine_lumbar_extension_notes: yup.string().optional(),
      joint_spine_lumbar_lateral_flexion_left_rom: yup.string().optional(),
      joint_spine_lumbar_lateral_flexion_left_notes: yup.string().optional(),
      joint_spine_lumbar_lateral_flexion_right_rom: yup.string().optional(),
      joint_spine_lumbar_lateral_flexion_right_notes: yup.string().optional(),
      joint_spine_lumbar_rotation_left_rom: yup.string().optional(),
      joint_spine_lumbar_rotation_left_notes: yup.string().optional(),
      joint_spine_lumbar_rotation_right_rom: yup.string().optional(),
      joint_spine_lumbar_rotation_right_notes: yup.string().optional(),
      joint_spine_lumbar_special_tests: yup.string().optional(),
      joint_upper_limb_shoulder_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_extension_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_extension_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_extension_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_extension_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_abduction_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_abduction_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_abduction_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_abduction_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_adduction_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_adduction_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_adduction_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_adduction_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_internal_rotation_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_internal_rotation_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_internal_rotation_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_internal_rotation_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_external_rotation_left_rom: yup.string().optional(),
      joint_upper_limb_shoulder_external_rotation_left_notes: yup.string().optional(),
      joint_upper_limb_shoulder_external_rotation_right_rom: yup.string().optional(),
      joint_upper_limb_shoulder_external_rotation_right_notes: yup.string().optional(),
      joint_upper_limb_shoulder_special_tests: yup.string().optional(),
      joint_upper_limb_elbow_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_elbow_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_elbow_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_elbow_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_elbow_extension_left_rom: yup.string().optional(),
      joint_upper_limb_elbow_extension_left_notes: yup.string().optional(),
      joint_upper_limb_elbow_extension_right_rom: yup.string().optional(),
      joint_upper_limb_elbow_extension_right_notes: yup.string().optional(),
      joint_upper_limb_elbow_special_tests: yup.string().optional(),
      joint_upper_limb_forearm_supination_left_rom: yup.string().optional(),
      joint_upper_limb_forearm_supination_left_notes: yup.string().optional(),
      joint_upper_limb_forearm_supination_right_rom: yup.string().optional(),
      joint_upper_limb_forearm_supination_right_notes: yup.string().optional(),
      joint_upper_limb_forearm_pronation_left_rom: yup.string().optional(),
      joint_upper_limb_forearm_pronation_left_notes: yup.string().optional(),
      joint_upper_limb_forearm_pronation_right_rom: yup.string().optional(),
      joint_upper_limb_forearm_pronation_right_notes: yup.string().optional(),
      joint_upper_limb_wrist_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_wrist_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_wrist_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_wrist_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_wrist_extension_left_rom: yup.string().optional(),
      joint_upper_limb_wrist_extension_left_notes: yup.string().optional(),
      joint_upper_limb_wrist_extension_right_rom: yup.string().optional(),
      joint_upper_limb_wrist_extension_right_notes: yup.string().optional(),
      joint_upper_limb_wrist_radial_deviation_left_rom: yup.string().optional(),
      joint_upper_limb_wrist_radial_deviation_left_notes: yup.string().optional(),
      joint_upper_limb_wrist_radial_deviation_right_rom: yup.string().optional(),
      joint_upper_limb_wrist_radial_deviation_right_notes: yup.string().optional(),
      joint_upper_limb_wrist_ulnar_deviation_left_rom: yup.string().optional(),
      joint_upper_limb_wrist_ulnar_deviation_left_notes: yup.string().optional(),
      joint_upper_limb_wrist_ulnar_deviation_right_rom: yup.string().optional(),
      joint_upper_limb_wrist_ulnar_deviation_right_notes: yup.string().optional(),
      joint_upper_limb_wrist_special_tests: yup.string().optional(),
      joint_upper_limb_fingers_mcp_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_fingers_mcp_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_fingers_mcp_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_fingers_mcp_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_fingers_pip_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_fingers_pip_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_fingers_pip_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_fingers_pip_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_fingers_dip_flexion_left_rom: yup.string().optional(),
      joint_upper_limb_fingers_dip_flexion_left_notes: yup.string().optional(),
      joint_upper_limb_fingers_dip_flexion_right_rom: yup.string().optional(),
      joint_upper_limb_fingers_dip_flexion_right_notes: yup.string().optional(),
      joint_upper_limb_fingers_abduction_left_rom: yup.string().optional(),
      joint_upper_limb_fingers_abduction_left_notes: yup.string().optional(),
      joint_upper_limb_fingers_abduction_right_rom: yup.string().optional(),
      joint_upper_limb_fingers_abduction_right_notes: yup.string().optional(),
      joint_upper_limb_fingers_special_tests: yup.string().optional(),
      joint_lower_limb_hip_flexion_left_rom: yup.string().optional(),
      joint_lower_limb_hip_flexion_left_notes: yup.string().optional(),
      joint_lower_limb_hip_flexion_right_rom: yup.string().optional(),
      joint_lower_limb_hip_flexion_right_notes: yup.string().optional(),
      joint_lower_limb_hip_extension_left_rom: yup.string().optional(),
      joint_lower_limb_hip_extension_left_notes: yup.string().optional(),
      joint_lower_limb_hip_extension_right_rom: yup.string().optional(),
      joint_lower_limb_hip_extension_right_notes: yup.string().optional(),
      joint_lower_limb_hip_abduction_left_rom: yup.string().optional(),
      joint_lower_limb_hip_abduction_left_notes: yup.string().optional(),
      joint_lower_limb_hip_abduction_right_rom: yup.string().optional(),
      joint_lower_limb_hip_abduction_right_notes: yup.string().optional(),
      joint_lower_limb_hip_adduction_left_rom: yup.string().optional(),
      joint_lower_limb_hip_adduction_left_notes: yup.string().optional(),
      joint_lower_limb_hip_adduction_right_rom: yup.string().optional(),
      joint_lower_limb_hip_adduction_right_notes: yup.string().optional(),
      joint_lower_limb_hip_internal_rotation_left_rom: yup.string().optional(),
      joint_lower_limb_hip_internal_rotation_left_notes: yup.string().optional(),
      joint_lower_limb_hip_internal_rotation_right_rom: yup.string().optional(),
      joint_lower_limb_hip_internal_rotation_right_notes: yup.string().optional(),
      joint_lower_limb_hip_external_rotation_left_rom: yup.string().optional(),
      joint_lower_limb_hip_external_rotation_left_notes: yup.string().optional(),
      joint_lower_limb_hip_external_rotation_right_rom: yup.string().optional(),
      joint_lower_limb_hip_external_rotation_right_notes: yup.string().optional(),
      joint_lower_limb_hip_special_tests: yup.string().optional(),
      joint_lower_limb_knee_flexion_left_rom: yup.string().optional(),
      joint_lower_limb_knee_flexion_left_notes: yup.string().optional(),
      joint_lower_limb_knee_flexion_right_rom: yup.string().optional(),
      joint_lower_limb_knee_flexion_right_notes: yup.string().optional(),
      joint_lower_limb_knee_extension_left_rom: yup.string().optional(),
      joint_lower_limb_knee_extension_left_notes: yup.string().optional(),
      joint_lower_limb_knee_extension_right_rom: yup.string().optional(),
      joint_lower_limb_knee_extension_right_notes: yup.string().optional(),
      joint_lower_limb_knee_special_tests: yup.string().optional(),
      joint_lower_limb_ankle_dorsiflexion_left_rom: yup.string().optional(),
      joint_lower_limb_ankle_dorsiflexion_left_notes: yup.string().optional(),
      joint_lower_limb_ankle_dorsiflexion_right_rom: yup.string().optional(),
      joint_lower_limb_ankle_dorsiflexion_right_notes: yup.string().optional(),
      joint_lower_limb_ankle_plantarflexion_left_rom: yup.string().optional(),
      joint_lower_limb_ankle_plantarflexion_left_notes: yup.string().optional(),
      joint_lower_limb_ankle_plantarflexion_right_rom: yup.string().optional(),
      joint_lower_limb_ankle_plantarflexion_right_notes: yup.string().optional(),
      joint_lower_limb_ankle_inversion_left_rom: yup.string().optional(),
      joint_lower_limb_ankle_inversion_left_notes: yup.string().optional(),
      joint_lower_limb_ankle_inversion_right_rom: yup.string().optional(),
      joint_lower_limb_ankle_inversion_right_notes: yup.string().optional(),
      joint_lower_limb_ankle_eversion_left_rom: yup.string().optional(),
      joint_lower_limb_ankle_eversion_left_notes: yup.string().optional(),
      joint_lower_limb_ankle_eversion_right_rom: yup.string().optional(),
      joint_lower_limb_ankle_eversion_right_notes: yup.string().optional(),
      joint_lower_limb_ankle_special_tests: yup.string().optional(),
      joint_lower_limb_toes_great_flexion_left_rom: yup.string().optional(),
      joint_lower_limb_toes_great_flexion_left_notes: yup.string().optional(),
      joint_lower_limb_toes_great_flexion_right_rom: yup.string().optional(),
      joint_lower_limb_toes_great_flexion_right_notes: yup.string().optional(),
      joint_lower_limb_toes_great_extension_left_rom: yup.string().optional(),
      joint_lower_limb_toes_great_extension_left_notes: yup.string().optional(),
      joint_lower_limb_toes_great_extension_right_rom: yup.string().optional(),
      joint_lower_limb_toes_great_extension_right_notes: yup.string().optional(),
      joint_lower_limb_toes_lesser_flexion_left_rom: yup.string().optional(),
      joint_lower_limb_toes_lesser_flexion_left_notes: yup.string().optional(),
      joint_lower_limb_toes_lesser_flexion_right_rom: yup.string().optional(),
      joint_lower_limb_toes_lesser_flexion_right_notes: yup.string().optional(),
      joint_lower_limb_toes_lesser_extension_left_rom: yup.string().optional(),
      joint_lower_limb_toes_lesser_extension_left_notes: yup.string().optional(),
      joint_lower_limb_toes_lesser_extension_right_rom: yup.string().optional(),
      joint_lower_limb_toes_lesser_extension_right_notes: yup.string().optional(),
      joint_lower_limb_toes_abduction_left_rom: yup.string().optional(),
      joint_lower_limb_toes_abduction_left_notes: yup.string().optional(),
      joint_lower_limb_toes_abduction_right_rom: yup.string().optional(),
      joint_lower_limb_toes_abduction_right_notes: yup.string().optional(),
      joint_lower_limb_toes_special_tests: yup.string().optional(),
      jointEvaluation_notes: yup.string().optional(),
    }).optional(),

    // Posture Evaluation
    postureFindings: yup.string().optional().max(500, 'Max 500 characters'),

    // Gait Evaluation
    gaitAnalysis: yup.string().optional().max(500, 'Max 500 characters'),

    // Special Tests
    specialTests: yup.string().optional().max(500, 'Max 500 characters'),

    // Diagnosis
    diagnosis: yup.string().required('Diagnosis is required').max(500, 'Max 500 characters'),

    // Treatment Plan
    shortTermGoals: yup.string().optional().max(500, 'Max 500 characters'),
    longTermGoals: yup.string().optional().max(500, 'Max 500 characters'),
    interventions: yup.string().optional().max(1000, 'Max 1000 characters'),
});
